# === Build/output ===
[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

# Use Node 18 for the whole build & functions
[build.environment]
  NODE_VERSION = "18"

# === Functions (global defaults) ===
[functions]
  node_bundler          = "esbuild"
  # keep nodemailer external so the bundler doesn’t try to inline it
  external_node_modules = ["nodemailer"]

# If you ever need per-function settings, you can add:
# [functions."contact"]
#   included_files = []

# === Long-cache headers for media ===
[[headers]]
  for = "/bg-*.webm"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/bg-*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/bg-poster.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# === API route -> Netlify Function (place BEFORE SPA fallback) ===
[[redirects]]
  from   = "/api/contact"
  to     = "/.netlify/functions/contact"
  status = 200
  force  = true

# === SPA fallback (keep last) ===
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
