# === Build/output ===
[build]
  command   = "npm run build"
  publish   = "dist"
  functions = "netlify/functions"

# === Functions config ===
[functions]
  node_bundler          = "esbuild"
  # keep nodemailer external so esbuild won't try to inline native deps
  external_node_modules = ["nodemailer"]

# (Do NOT set node_version here. Set Node in Site settings > Environment > Node version = 18)

# === Long-cache headers for media ===
[[headers]]
  for = "/bg-*.webm"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/bg-*.mp4"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/bg-poster.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# === API route -> Netlify Function (must come BEFORE SPA fallback) ===
[[redirects]]
  from   = "/api/contact"
  to     = "/.netlify/functions/contact"
  status = 200
  force  = true

# === SPA fallback (keep last) ===
[[redirects]]
  from   = "/*"
  to     = "/index.html"
  status = 200
